.TH \f3bhconf\f1 1 "Time-stamp: <2002-05-09 21:32:19 fip>"
.SH NAME
bhconf \- rules setup script for the 
.B blackhole
spam blocker.
.SH SYNOPSIS
.B bhconf
[queue] [configfile]
.SH DESCRIPTION

.B bhconf
is a shell script which is intended to make easier the setup and maintenance
of your personal rules for spam filtering.
.P

.SH SEE ALSO
.BR bhinstall (1),
.BR blackhole (1),
.BR dot_blackhole (5)

.PP
For a verbose intro see the 
.B blackhole
info entry.
.SH AUTHOR
.SB Chris Kennedy

.I <getdown@groovy.org>
.P
This manual page was written by 
.SB Michael Hummel 
.SM <mhummel@debian.org>,
.SM for the 
.SB Debian GNU/Linux system
.SM (but may be used by others).
